django four projects/Brijesh Projects/yantragenefolder/yantragene/aboutus/urls.py
from django.conf.urls import url
from . import views

# app_name = 'aboutus'

urlpatterns = [
	url(r'^$', views.about_view, name="aboutus"),
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/accounts/urls.py
from django.conf.urls import url
from . import views

# app_name = "accounts"

urlpatterns = [
	url(r'^register/$', views.register_view, name="register"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	#url(r'^profile/(?P<id>\d+)/$', views.profile_view, name="profile"),
	url(r'^delete/(?P<id>\d+)/(?P<proid>\d+)/$', views.delete_event, name="delete"),
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/events/urls.py
from django.conf.urls import url
from . import views


# app_name = "events"

urlpatterns = [

	url(r'^$', views.events_view, name='events'),
	url(r'^detail/(?P<id>\d+)/', views.event_detail, name="detail"),
	url(r'^register/$', views.register_view, name="register"),
	
	
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/gallery/urls.py
from django.conf.urls import url

from . import views

# app_name = "gallery"

urlpatterns = [

	url(r'^$', views.gallery_view, name="gallery")
	
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/home/urls.py
from django.conf.urls import url 
from . import views

# app_name = 'home'

urlpatterns = [
	url(r'^$', views.home_view, name="home")
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/yantragene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^aboutus/', include('aboutus.urls', namespace='aboutus')),
    url(r'^contactus/', include('contactus.urls', namespace='contactus')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	
	<meta charset="utf-8">
	<title>Yantragene 2k19</title>
	<link rel="shortcut icon" href={% static 'images/website-icon.png' %} type="image/x-icon">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href={% static "css/base.css" %}>
	<script type="text/javascript" src={% static "javascript/base.js" %}></script>
	<style type="text/css">
		
		body{	
			background-image:url('{% static "images/bg-image1.jpg" %}');

		}

	</style>

	{% block head %}
	{% endblock %}

</head>
<body>
	
	<div id="#nav_bar">
	<nav class="navbar navbar-inverse navbar-fixed-top">
	    
	    <div class="navbar-header">
	        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	        </button>
	        <img id="yantra_icon"src={% static 'images/website-icon.png' %}/>
	    </div>
	    
	    <div id="navbarCollapse" class="collapse navbar-collapse">
	        <ul class="nav navbar-nav">
	          <li class=""><a href="#"></a></li>

		      <li><a class="navbar-brand" href="{% url 'home:home' %}">Yantragene@2k19</a></li>
		      <li id="home_nav"><a href="{% url 'home:home' %}">Home</a></li>
		      <li id="event_nav"><a href="{% url 'events:events' %}">Events</a></li>
		      <li id="note_nav"><a href="{% url 'notifications:notifications' %}">Notifications</a></li>
		      <li id="aboutus_nav"><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
		      <li id="gallery_nav"><a href="{% url 'gallery:gallery' %}">Gallery</a></li>
		      <li id="contact_nav"><a href="{% url 'contactus:contactus' %}">Contact Us</a></li>
		      
	        
	        	{% if user.is_authenticated %}
	        		
	        		<li id="welcome_nav" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Welcome {{ user.first_name }}<span class="caret"></span></a>
			        <ul class="dropdown-menu">
			          <li><a href="{% url 'accounts:profile' id=user.profile.id %}">View Profile</a></li>
			          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
			          
			        </ul>
			      </li>

	        	{% else %}
	        		<li id="register_nav"><a href="{% url 'accounts:login' %}">Register/Login</a></li>
	        	{% endif %}
	            
	        	
	        </ul>
	    </div>
	</nav>
	</div>
	<br><br><br>


	{% block body %}
	{% endblock %}

</body>
</html>

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/base_events_page.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Yantragene 2k19</title>
	<link rel="shortcut icon" href={% static 'images/website-icon.png' %} type="image/x-icon">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script type="text/javascript" src={% static "javascript/base_events_js.js" %}></script>
	
	<style type="text/css">

		body{	
			background-image:url('{% static "images/bg-image1.jpg" %}');

		}

		#event_name{
			color:aquamarine;
			font-family: Modern;
			font-size:7vw;
		}
		#heading_row{
			height:40px;
		}
		.topics{
			color:#B3B6B7;
			font-size:30px;
			text-align:center;
			cursor:pointer;
		}
		.topics:hover{
			color:#F0F3F4;

		}

		/*  events detail page css*/

		#desc_div, #rules_div, #cord_div, #reg_div {
			/*height:300px;*/
			
			border-radius: 5px;
			background:white;
			color:#17202A;

		}
		#rules_div, #cord_div, #reg_div{
			display:none;
		}
		#desc_div{
			display:block;
		}

		.cross{
			position:relative;
			top:3px;
			left:99%;
			width:20px;
			height:20px;
			float:left;
			background:white;
		}


	</style>
	
	{% block head %}
	{% endblock %}

</head>
<body>

	<center><h1 id="event_name">{{event_title}}</h1></center>

	<div class="container-fluid">
		<div id="heading_row" class="row">
			<div class="col-md-3 col-sm-10">
				<div>
					<h1 class="topics" id="desc_btn">Description</h1>
				</div>
			</div>
			<div class="col-md-3 col-sm-10">
				<div>
					<h1 class="topics" id="rules_btn">Rules And Regulations</h1>
				</div>
			</div>
			<div class="col-md-3 col-sm-10">
				<div>
					<h1 class="topics" id="cord_btn">Coordinators</h1>
				</div>
			</div>
			<div class="col-md-3 col-sm-10">
				<div>
					<h1 class="topics" id="reg_btn">Register</h1>
				</div>
			</div>
		</div>
		




		<div class="row">

		
			<div id="desc_div" class="col-md-6 col-lg-6 col-md=offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">

				<img class="cross" src="{% static 'images/cross1.png' %}">
				<center><h3>Description</h3></center>
				{% block desc %}
				{% endblock %}
				
		

			</div>


			<div id="rules_div" class="col-md-6 col-lg-6 col-md=offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
				<img class="cross" src="{% static 'images/cross1.png' %}">
				<center><h3>Rules And Regulations</h3></center>
				{% block rules %}
				{% endblock %}
				

			</div>


			<div id="cord_div" class="col-md-6 col-lg-6 col-md=offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
				<img class="cross" src="{% static 'images/cross1.png' %}">
				<center><h3>Coordinators</h3></center>
				{% if coordinator %}
					
					<div class="row">
						
						{% for c in coordinator %} 

							<div class="col-lg-6 col-md-6 col-sm-10">
								<center>
								<img style="height:200px;width:200px;" src="{{ c.cimage.url }}" alt="{{c.cname}}" class="cord_image img-responsive img-rounded" />
								
									<p class="pp"><b>{{c.cname}}</b></p>
									<p class="pp"><span class="glyphicon glyphicon-earphone"><b> {{c.cmobile}}</b></span></p>
									<p class="pp"><span class="glyphicon glyphicon-envelope"><b> <a href="https://gmail.com">{{c.cemail}}</a></b></span></p>

									<style type="text/css">
										.pp, a {
											color:#1C2833;
											font-family: arial;
										}

									</style>

								</center>
							</div>
							
						{% endfor %}
						
					</div>
					
				{% else %}
					<h1>No details for now</h1>
				{% endif %}
				
				
			</div>


			<div id="reg_div" class="col-md-6 col-lg-6 col-md=offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
				<img class="cross" src="{% static 'images/cross1.png' %}">
				<center><h3>Register</h3></center>

				{% block reg %}
				{% endblock %}

			</div>
		</div>	
	</div>
	
</body>
</html>