django four projects/Brijesh Projects/yantragenefolder/yantragene/accounts/urls.py
from django.conf.urls import url
from . import views

# app_name = "accounts"

urlpatterns = [
	url(r'^register/$', views.register_view, name="register"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	#url(r'^profile/(?P<id>\d+)/$', views.profile_view, name="profile"),
	url(r'^delete/(?P<id>\d+)/(?P<proid>\d+)/$', views.delete_event, name="delete"),
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/events/urls.py
from django.conf.urls import url
from . import views


# app_name = "events"

urlpatterns = [

	url(r'^$', views.events_view, name='events'),
	url(r'^detail/(?P<id>\d+)/', views.event_detail, name="detail"),
	url(r'^register/$', views.register_view, name="register"),
	
	
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/home/urls.py
from django.conf.urls import url 
from . import views

# app_name = 'home'

urlpatterns = [
	url(r'^$', views.home_view, name="home")
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/yantragene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^aboutus/', include('aboutus.urls', namespace='aboutus')),
    url(r'^contactus/', include('contactus.urls', namespace='contactus')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django four projects/Brijesh Projects/yantragenefolder/yantragene/events/models.py
from django.db import models
from accounts.models import Profile
class Department(models.Model):
	
	did = models.IntegerField()
	dname = models.CharField(max_length=50)
	dimage = models.ImageField(upload_to='images/departments', blank=True)

	def __str__(self):
		return self.dname


class Events(models.Model):
	
	eid = models.IntegerField()
	ename = models.CharField(max_length=30)
	department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)


	def __str__(self):
		return self.ename

class Coordinator(models.Model):
	
	cname = models.CharField(max_length=20)
	cmobile = models.CharField(max_length=13)
	cemail = models.EmailField()
	cimage = models.ImageField(upload_to='images/coordinators', blank=True)
	events = models.ForeignKey(Events, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.cname


class Participant(models.Model):

	events = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
	team_name = models.CharField(max_length=30, blank=True, null=True)
	events_name = models.CharField(max_length=30, blank=True, null=True)
	member2 = models.CharField(max_length=50, blank=True, null=True)
	member3 = models.CharField(max_length=50, blank=True, null=True)
	member4 = models.CharField(max_length=50, blank=True, null=True)
	member5 = models.CharField(max_length=50, blank=True, null=True)

	def __str__(self):
		return self.team_name

django four projects/Brijesh Projects/yantragenefolder/yantragene/events/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import (

	Department,
	Events,
	Coordinator,
	Participant

	)
#from accounts.models import Profile


def events_view(request):

	department = Department.objects.all()
	events = Events.objects.all()

	outer_event_list = dict()
	
	for d in department:
		
		e = events.filter(department=d)
		outer_event_list[d] = e



	context = {
		'outer_event_list':outer_event_list
	}
	
	return render(request, 'events/events.html', context)



def event_detail(request, id=None):
	
	events = get_object_or_404(Events, id=id)
	coordinator = Coordinator.objects.filter(events=events)
	
	page = events.ename.lower()
	page = 'events/'+page+'.html'

	context = {
	
		'event_title' : events.ename.upper(),
		'events' : events,
		'coordinator' : coordinator

	}
	
	return render(request, page, context)


def register_view(request):
	
	team_name = request.GET['team_name']
	member2 = request.GET['member2']
	member3 = request.GET['member3']
	member4 = request.GET['member4']
	member5 = request.GET['member5']
	event_id = request.GET['event_id']
	profile_id = request.GET['profile_id']
	events_name = request.GET['events_name']

	t = Participant.objects.filter(team_name=team_name)
	if len(t):
		return render(request, 'events/events.html', {'msg':'Team name already existed'})

	t = Participant.objects.filter(events_name=events_name, profile=profile_id)
	if len(t):
		return render(request, 'events/events.html', {'msg':'You have already participated in this event'})

	p = Participant(

		team_name=team_name,
		events_name=events_name, 
		member2=member2, 
		member3=member3,
		member4=member4,
		member5=member5,
		events_id=event_id,
		profile_id=profile_id,

		)

	p.save()

	return HttpResponseRedirect(reverse('events:events'))

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/air fray.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/algosense.html
{% extends 'base_events_page.html' %}


{% block head %}
{% endblock %}



{% block desc %}	

	
	<ul class="list-unstyled">
		<li>Coding is a combination of artistry and engineering. So gear up everyone for the befalling event.</li>
		<li>“ALGOSENSE”, a bewildering platform to showcase your competency and mutation in fabricating the algorithm and programming.</li>
		<li>The event "ALGOSENSE" provides you with the opportunity to show and enhance your skills on Languages like “C”,”Java”,”Python” &”C++”.</li>
	</ul>
	<br>
	<h2>Judging Criteria</h2>
	<ul class="list-unstyled">
		<li>Accuracy of your output.</li>
		<li>Complexity of algorithm.</li>
		<li>Problem Solving Approach.</li>

	</ul>

{% endblock %}


{% block rules %}	
<ul class="list-unstyled">
	<li>The event will have 2 rounds.</li>
	<li>Maximum Team Size is 2 students.</li>
</ul>
<br>
<h2>1. Qualifier Round</h2>
<ul class="list-unstyled">
	<li>In this you will have 2 problems.</li>
	<li>Top 20% of competitors will qualify this round.</li>
	<li>Maximum 30 min will be given to solve the problem.</li>
	<li>The contestant will qualify the round as soon as he/she solves the 2 questions correctly.</li>
	<li>As soon as we will get the top 20% of the competitors the round will be called off.</li>
</ul>
<br>
<h2>2. Final Round</h2>
<ul class="list-unstyled">
	<li>In this you will have 5 problems.</li>
	<li>Top 2 competitors will be ranked 1st 2nd respectively.</li>
	<li>The marking will be done according to accuracy of your output.</li>
	<li>Maximum 90 min will be given to solve the problem.</li>
 </ul>



{% endblock %}


{% block reg %}	
	{% if user.is_authenticated %}
		<h3>Team Size : 2, Minimum : 1, Maximum : 2</h3>
		<p>You will be the first member</p>
		<form action="{% url 'events:register' %}" method="get">
			
			<label>Team Name:</label>
			<input class="form-control" type="text" name="team_name" placeholder="Enter Team Name" required="required">
			<label>Member 2 (Optional):</label>
			<input class="form-control" type="text" name="member2" placeholder="Enter 2nd member name" value="">
			<input class="form-control" type="hidden" name="member3" placeholder="Enter 2nd member name"
			value="">
			<input class="form-control" type="hidden" name="member4" placeholder="Enter 2nd member name"
			value="">
			<input class="form-control" type="hidden" name="member5" placeholder="Enter 2nd member name"
			value="">
			<input type="hidden" name="event_id" value="{{ events.id }}">
			<input type="hidden" name="events_name" value="{{ events.ename }}">
			<input type="hidden" name="profile_id" value="{{ user.profile.id }}"><br>

			<center>
				<input class="btn btn-default btn-success" type="submit" value="Submit">
				<input class="btn btn-default btn-info" type="reset" value="Reset">
			</center>

		</form>
		<br><br>
	{% else %}
		<h2>You are not logged in.</h2><br>
		<button class="btn btn-default btn-info"><a href="{% url 'accounts:login' %}">Click Here To Login/Register</a></button>
		<br>
	{% endif %}

{% endblock %}



			
{% block body %}
{% endblock %}

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/appmania.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/bridge - it.html
{% extends 'base_events_page.html' %}


{% block head %}
{% endblock %}



{% block desc %}

	<h3>Event Details</h3>
Design a bridge by using Popsicle sticks (ice cream sticks) satisfying the tated constraints.

<h3>Judging Criteria</h3><p>
First the structure will be reviewed to check if it violates any rules mentioned above.
Scoring of structure will be based on performance as well as aesthetics.
The bridge will be scored on how well the material has been used to support the load. The efficiency will be calculated as the ultimate load capacity and bridge weight.
Winner will be decided on the basis of maximum efficiency.
In case of any discrepancies, the decision taken by the Judges and the council will be the final verdict.	</p>
{% endblock %}


{% block rules %}
<h3>RULES AND REGULATIONS</h3><p>
A suspension bridge is to be constructed by the participants.
Use ice-cream sticks of standard dimensions.
Sticks can be altered physically, notched at any angles.
Only Fevicol can be used as adhesive, use of other adhesives may lead to disqualification.
Use of thread is allowed.</p>	
{% endblock %}


{% block cord %}
{% endblock %}


{% block reg %}
	{% if user.is_authenticated %}
		<h3>Team Size : 5, Minimum : 1</h3>
		<p>You will be the first member</p>
		<form action="{% url 'events:register' %}" method="get">
			
			<label>Team Name:</label>
			<input class="form-control" type="text" name="team_name" placeholder="Enter Team Name" required="required">
			<label>Member 2 (Optional):</label>
			<input class="form-control" type="text" name="member2" placeholder="Enter 2nd member name" value="">
			<label>Member 3 (Optional):</label>
			<input class="form-control" type="text" name="member3" placeholder="Enter 3nd member name" value="">
			<label>Member 4 (Optional):</label>
			<input class="form-control" type="text" name="member4" placeholder="Enter 4nd member name" value="">
			<label>Member 5 (Optional):</label>
			<input class="form-control" type="text" name="member5" placeholder="Enter 5nd member name" value="">
			<input type="hidden" name="event_id" value="{{ events.id }}">
			<input type="hidden" name="events_name" value="{{ events.ename }}">
			<input type="hidden" name="profile_id" value="{{ user.profile.id }}"><br>

			<center>
				<input class="btn btn-default btn-success" type="submit" value="Submit">
				<input class="btn btn-default btn-info" type="reset" value="Reset">
			</center>

		</form>
		<br><br>
	{% else %}
		<h2>You are not logged in.</h2><br>
		<button class="btn btn-default btn-info"><a href="{% url 'accounts:login' %}">Click Here To Login/Register</a></button>
		<br>
	{% endif %}	
{% endblock %}



			
{% block body %}
{% endblock %}

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/contraption.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/events.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<!--<link rel="stylesheet" type="text/css" href={% static "css/events.css" %}>-->
<!--<script type="text/javascript" src={% static "javascript/events.js" %}></script>-->

{% endblock %}

{% block body %}
<center><p style="color:red;">{{ msg }}</p></center>
<div class="container-fluid">
	<center><h1 id="ev_header">Events</h1></center>
	<div class="row">
		<div id="fade_view">
		{% if outer_event_list %}
			{% for d,elist in outer_event_list.items %}

				
				<div class="col-md-3 col-lg-3 col-sm-10">
				    <div class="thumbnail dept_box">
				      
				        <img src="{{ d.dimage.url }}" alt="{{d.dname}}" style="width:100%">
				        <div class="caption">
				          	<center><h3>{{d.dname}}</h1></center>
				        </div>
				        <ul class="list-unstyled">
				        {% for e in elist %}

				        	<center><li><p><b><a href="{% url 'events:detail' id=e.id %}">{{e.ename}}</a></b></p></li></center>
				        		
			        	{% endfor %}
				        </ul>
				     
				    </div>
				</div>



	    	{% endfor %}
	    {% else %}
			<h1>No Data</h1>
		{% endif %}
		</div>
	
</div>

<style>
	h1{
		color:#E5E7E9;
	}
	h3{
		color:#2C3E50;
	}
	.dept_box{
		height:410px;
	}
	img{
		width:200px;
		height: 200px;
		margin:3px;
	}
	p{

		color:black;
		font-family:tahoma;
	}
	p:hover{
		text-decoration: none !important;
		color:#566573;
	}
	#fade_view,#ev_header{
		display:none;
	}
	
</style>

{% endblock %}
</div>

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/modechex.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/photoshop.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/robbo soccer.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/robo race.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/sky rc.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/techyshot.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/webbit.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/events/zumo war.html
{% extends 'base_events_page.html' %}


	{% block head %}
	{% endblock %}



	{% block desc %}	
	{% endblock %}


	{% block rules %}	
	{% endblock %}


	{% block cord %}
	{% endblock %}


	{% block reg %}	
	{% endblock %}


	
				
	{% block body %}
	{% endblock %}

	