django four projects/Brijesh Projects/yantragenefolder/yantragene/accounts/urls.py
from django.conf.urls import url
from . import views

# app_name = "accounts"

urlpatterns = [
	url(r'^register/$', views.register_view, name="register"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	#url(r'^profile/(?P<id>\d+)/$', views.profile_view, name="profile"),
	url(r'^delete/(?P<id>\d+)/(?P<proid>\d+)/$', views.delete_event, name="delete"),
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/events/urls.py
from django.conf.urls import url
from . import views


# app_name = "events"

urlpatterns = [

	url(r'^$', views.events_view, name='events'),
	url(r'^detail/(?P<id>\d+)/', views.event_detail, name="detail"),
	url(r'^register/$', views.register_view, name="register"),
	
	
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/home/urls.py
from django.conf.urls import url 
from . import views

# app_name = 'home'

urlpatterns = [
	url(r'^$', views.home_view, name="home")
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/yantragene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^aboutus/', include('aboutus.urls', namespace='aboutus')),
    url(r'^contactus/', include('contactus.urls', namespace='contactus')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django four projects/Brijesh Projects/yantragenefolder/yantragene/accounts/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	mobile = models.CharField(max_length=20, null=True)
	
	

	def __str__(self):
		return self.mobile

django four projects/Brijesh Projects/yantragenefolder/yantragene/accounts/views.py
from django.conf import settings
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import (

	authenticate,
	login,
	logout

	)

from .models import Profile
from events.models import Participant


def register_view(request):
	if request.method=="POST":
		first_name=request.POST['fname']
		last_name=request.POST['lname']
		username=request.POST['uname']
		password=request.POST['pwd']
		cpassword=request.POST['cpwd']
		email=request.POST['email']
		mobile=request.POST['mobile']

		u = User.objects.filter(username=username)
		if len(u):
			return render(request,'accounts/register.html', {'msg':"Username already been taken"})
		e = User.objects.filter(email=email)
		if len(e):
			return render(request,'accounts/register.html', {'msg':"Email Already registered"})
		if len(mobile)!=10:
			return render(request,'accounts/register.html', {'msg':"Please enter Correct Mobile Number"})
		m = Profile.objects.filter(mobile=mobile)
		if len(m):
			return render(request,'accounts/register.html', {'msg':"Mobile number already existed"})
		if password!=cpassword:
			return render(request,'accounts/register.html', {'msg':"Password And Confirm Password Did not Match"})

		user, create = User.objects.get_or_create(
			
			first_name=first_name,
			last_name=last_name,
			username=username,
			email=email,

			)
		
		user.set_password(password)
		user.save()
		pro = Profile(mobile=mobile, user=user)
		pro.save()

		return HttpResponseRedirect(reverse('accounts:login'))
	else:
		return render(request,'accounts/register.html', {'msg':""})

def login_view(request):
	if request.method=="POST":
		username=request.POST['uname']
		password=request.POST['pwd']
		try:
			user = authenticate(username=username,password=password)
			if user is not None:
				login(request, user)
				return HttpResponseRedirect(reverse('home:home'))

			else:
				return render(request, 'accounts/login.html', {'msg':"Wrong Username Or Password"})
		except:
			return render(request, 'accounts/login.html', {'msg':"Sorry, Error In Login"})
	else:
		return render(request, 'accounts/login.html', {'msg':""})

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('home:home'))


def profile_view(request, id=None):
	participant = Participant.objects.filter(profile=id)
	context = {
		'participant':participant,
		'length':len(participant)
	}

	return render(request, 'accounts/profile.html', context)

def delete_event(request, id=None, proid=None):
	
	try:
		p = Participant.objects.get(id=id)
		p.delete()
	except:
		pass
	finally:
		return HttpResponseRedirect(reverse('accounts:profile', kwargs={'id': proid }))

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
	<script type="text/javascript" src={% static "javascript/register.js" %}></script>
{% endblock %}
{% block body %}
	
	<div class="row">
		<div class="col-md-4 col-md-offset-4 col-sm-10 col-sm-offset-1">
			<form action="" method="post">
				<center><p style="color:red;">{{msg}}</p></center>
				{% csrf_token %}

				<label>Username:</label>
				<input type="text" name="uname" required='required' placeholder="Enter Your Username" class="form-control"><br>

				<label>Password:</label>
				<input type="password" name="pwd" required='required' placeholder="Password" class="form-control"><br>

				<center>
						<input type="submit" value="Submit" class="btn btn-default btn-success">
						<input type="reset" value="Reset" class="btn btn-default btn-info">
				</center>

			</form>
		</div>
	</div>
	<br><br>
	<center>
		<p id="click_link"><a href="/accounts/register/"><b>Create Your Account</b></a></p>
	</center>
	<style type="text/css">
		a,label, #click_link{
			color:white;
		}
	</style>
{% endblock %}

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
	<script type="text/javascript" src={% static "javascript/profile.js" %}></script>
{% endblock %}
{% block body %}
	<div class="row">
	<div class="col-md-4 col-md-offset-4 col-sm-10 col-sm-offset-1">
	{% if user.is_authenticated %}
		<center><h2 class="white">Welcome {{ user.first_name }} {{ user.last_name }}</h2></center>
		<center><h3 class="white">Your Details:</h2></center>
		<center><p class="white"><b>Your Email : </b>{{user.email}}</p></center>
		<center><p class="white"><b>Your Mobile No. : </b>{{user.profile.mobile}}</p></center>
		<h3 class="white">Your partipation(s):</h3>
		{% if length %}
			{% for p in participant %}
			<div class="well part_div">
				<h3><b>Team Name : </b>{{p.team_name}}</h3>
				<h3><b>Event Name : </b>{{p.events_name}}</h3>
				<h4><b>Member(s) :</b>You, {{p.member2}} {{p.member3}} {{pt.member4}}</h4>
				<button class="btn btn-default btn-danger">
					<a href="{% url 'accounts:delete' id=p.id proid=user.profile.id %}" onclick="return confirm('Are you sure?')">Remove</a>
				</button>
			</div>
			{% endfor %}
		
		{% else %}
			<p class="white">You have Not Participated in any event yet.</p>
			<button class="btn btn-default btn-info">
					<a href="{% url 'events:events' %}">Paricipate</a>
				</button>
		{% endif %}
		{% else %}
			<p class="white">You have Not Participated in any event.</p>
		{% endif %}
	<br>
	


	</div>
	</div>
	<style type="text/css">
		.white,a{
			color:white;
			font-family: tahoma;
		}
		.part_div{
			background:white;
			border:1px solid yellow;
			border-radius:5px;
			color:#273746;
		}
		a:hover{
			color:white;
		}
	</style>
{% endblock %}

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
	<script type="text/javascript" src={% static "javascript/register.js" %}></script>
{% endblock %}
{% block body %}
	
	<div class="row">
		<div class="col-md-4 col-md-offset-4 col-sm-10 col-sm-offset-1">
			<form action="" method="post">
				<center><p style="color:red;">{{msg}}</p></center>
				{% csrf_token %}
				<label>First Name:</label>
				<input type="text" name="fname" required='required' placeholder="Your first name" class="form-control"><br>

				<label>Last Name:</label>
				<input type="text" name="lname" required='required' placeholder="Your Last name" class="form-control"><br>

				<label>Username:</label>
				<input type="text" name="uname" required='required' placeholder="Preffered Username" class="form-control"><br>

				<label>Password:</label>
				<input type="password" name="pwd" required='required' placeholder="Password" class="form-control"><br>

				<label>Confirm Password:</label>
				<input type="password" name="cpwd" required='required' placeholder="Confirm Password" class="form-control"><br>

				<label>Email:</label>
				<input type="email" name="email" required='required' placeholder="Your email address" class="form-control"><br>

				<label>Mobile No.:</label>
				<input type="text" name="mobile" required='required' placeholder="Your Mobile No." class="form-control"><br>

				
				<center>
						<input type="submit" value="Submit" class="btn btn-default btn-success">
						<input type="reset" value="Reset" class="btn btn-default btn-info">
				</center>

			</form>
		</div>
	</div>
	<style type="text/css">
		label{
			color:white;
		}
	</style>
{% endblock %}