django four projects/Brijesh Projects/yantragenefolder/yantragene/contactus/urls.py
from django.conf.urls import url

from . import views

# app_name = "contactus"

urlpatterns = [
	url(r'^$', views.contactus_view, name="contactus"),
	url(r'^feedback/$', views.feedback_view, name="feedback"),
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/home/urls.py
from django.conf.urls import url 
from . import views

# app_name = 'home'

urlpatterns = [
	url(r'^$', views.home_view, name="home")
]

django four projects/Brijesh Projects/yantragenefolder/yantragene/yantragene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^aboutus/', include('aboutus.urls', namespace='aboutus')),
    url(r'^contactus/', include('contactus.urls', namespace='contactus')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django four projects/Brijesh Projects/yantragenefolder/yantragene/contactus/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
	name = models.CharField(max_length=40)
	email = models.EmailField()
	review = models.CharField(max_length=250)

	def __str__(self):
		return self.name

django four projects/Brijesh Projects/yantragenefolder/yantragene/contactus/forms.py
from django import forms

class FeedbackForm(forms.Form):
	name = forms.CharField(label="Your name",
			widget=forms.TextInput(
					attrs={
						'class':'form-control',
						'placeholder':'Enter Your name'
					}
				)
		)

	email = forms.CharField(label="Your Email",
			widget=forms.EmailInput(
					attrs={
						'class':'form-control',
						'placeholder':'Enter Your Email'
					}
				)
		)

	review = forms.CharField(label="Your Feedback",
			widget=forms.TextInput(
					attrs={
						'class':'form-control',
						'placeholder':'Your Feedback'
					}
				)
		)

django four projects/Brijesh Projects/yantragenefolder/yantragene/contactus/views.py
from django.shortcuts import render
from .models import Feedback
from .forms import FeedbackForm

# Create your views here.
def contactus_view(request):
	form = FeedbackForm()
	return render(request, 'contactus/contactus.html', {'form':form})

def feedback_view(request):
	
	name = request.GET['name']
	email = request.GET['email']
	review = request.GET['review']

	f1 = Feedback(name=name, email=email, review=review)
	f1.save()

	form = FeedbackForm()
	return render(request, 'contactus/contactus.html', {'form':form})

django four projects/Brijesh Projects/yantragenefolder/yantragene/templates/contactus/contactus.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
	<script type="text/javascript" src={% static "javascript/contact.js" %}></script>
{% endblock %}

{% block body %}

	<center style="color:white;"><h1>REACH US</h1></center>
	<div class="container">
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<div class="mapouter">
				<div class="gmap_canvas">
					<iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=feroze%20gandhi%20institute%20raebareli&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
					<a href="https://www.maps-erstellen.de">maps-erstellen.de</a>
				</div>

			</div>
		</div>
		<div class="col-md-5 col-md-offset-1 col-sm-12" id="content">
			<p><b>Call us on</b> : 7007514827, 896084564</p>
			<p><b>Mail us at</b> : fest@yantragene.co.in</p>
			<p><b>Our college website is</b> : <a href="https://fgiet.ac.in">fgiet.ac.in</a></p>
			<p>Feroze Gandhi Institute Of Engineering AndTechnology,</p>
			<p>Lucknow Road, Near Ratapur Chauraha,</p> 
			<p>Ratapur, Raebareli,</p>
			<p>Uttar Pradesh 229316, India</p>
			
			<center><h3>Send Us Your Feedback</h3></center>
			<form action="{% url 'contactus:feedback' %}" method="get">
				{{form}}
				<br>
				<center>
					<input type="submit" value="Send" class="btn btn-default btn-small btn-success" onclick="alert('We apppreciate your suggestion')">
					<input type="reset" value="Reset" class="btn btn-default btn-small btn-info">
				</center>
			</form>
		</div>

	</div>
	</div>
	<style>
		.mapouter{
			text-align:right;
			height:500px;
			width:600px;
		}
		.gmap_canvas {overflow:hidden;
			background:none!important;
			height:500px;
			width:600px;
		}
		#content{
			color:#D0D3D4;
			border:2px solid #D0D3D4;
			border-radius: 5px;
			font-size:15px;
			font-family: tahoma;
		}
	</style>

{% endblock %}